---
author: Emin Eker
description: Folyolar
email: emineker@gmail.com
url: fo.emineker.net
domain: emineker.net
intro: ''
googleanalytics: 'UA-40135421-1'
googleplus: '110754783365796157780'
brand: default
landslide: /usr/bin/landslide
css: _/default.css
js: _/default.js _/local.js
indextemplate: _/index.erb
foliotemplate: _/default.erb
