---
author: emineker
description: Folyolar
email: emineker@bil.omu.edu.tr
url: fo.emineker.net
domain: emineker.net
intro: ''
googleanalytics: 'UA-40135421-1'
googleplus: '110754783365796157780'
brand: default
landslide: /usr/bin/landslide
css: _/default.css
js: _/default.js
indextemplate: _/index.erb
foliotemplate: _/default.erb
